name: Python CICD

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create post traces directory
      run: mkdir -p post_traces

    - name: Run pylint
      run: pylint src/* > post_traces/pylint_traces.txt

    - name: Run autopep8
      run: autopep8 --recursive --in-place --aggressive --aggressive src/* > post_traces/pep8_traces.txt

    - name: Run Pyflakes
      run: pyflakes src/* > post_traces/pyflakes_traces.txt

    - name: Push post_traces folder
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add post_traces
        git diff --cached --exit-code || git commit -m "Post Traces"
        git push origin main

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest test/test.py --doctest-modules --junitxml=junit/test-results.xml --cov=./main --cov-report=xml --cov-report=html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}